export const POSTS_LOAD = "POSTS_LOAD";
export const LOADER_DISPLAY_ON = "LOADER_DISPLAY_ON";
export const LOADER_DISPLAY_OFF = "LOADER_DISPLAY_OFF";
export const MODAL_DISPLAY_ON = "MODAL_DISPLAY_ON";
export const MODAL_DISPLAY_OFF = "MODAL_DISPLAY_OFF";
export const POST_CREATE = "POST_CREATE";
